services:

  database:
    build: "database"
    environment:
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - my-network

  simple-api:
    build: "simple-api"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=pwd
    networks:
      - my-network

  httpd:
    build: "http-server"
    ports:
      - "80:80"
    networks:
      - my-network

  app-front:
    build: "app-front"  # Make sure your front-end has a Dockerfile in the 'frontend' directory
    environment:
      - API_URL=http://simple-api:80  # Replace PORT with your actual API port
    ports:
      - "8080:80"  # Exposing the front-end on port 8080
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-volume :