name: CI Backend Testing

on:
  push:
    branches:
      - main      # Trigger when code is pushed to the main branch
      - develop   # Optionally, also trigger when code is pushed to the develop branch
  pull_request:
    branches:
      - main      # Trigger when a pull request is made targeting the main branch

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4  # Checkout the code

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=malachaneG_tp-devops-correction-docker -Dsonar.organization=malachaneg -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml
        working-directory: simple-api
